### ISSUE TITLE
Measuring Events

### ISSUE THREAD

**Issue by hco** [danieldotnl/ha-measureit#179]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to count events. I have a button which only emits events, but would love to count them using measureit

### Describe the solution you'd like

Maybe similar to how templates can be defined, we could define events that are being matched?

### Describe alternatives you've considered

Right now I have a counter helper that I increment using an automation

### Additional context

-

**Comment by danieldotnl** [comment]
I have thought about it before, but decided against implementing this, since events are an advanced concept in HA, not really meant for the end user. It is also tricky to filter out the right event, especially if it is depending on data in the event.

I recommend to create an automation that listens to the event and updates a counter. You can then have MeasureIt measure the counter updates per day/week/month/etc.
I use something like this myself:

```yaml
alias: Flight counter
description: ""
mode: single
triggers:
  - event_type: flightradar24_entry
    trigger: event
conditions: []
actions:
  - metadata: {}
    data: {}
    target:
      entity_id: counter.flights_in_area
    action: counter.increment
```
